dist:
  module: go.opentelemetry.io/collector/cmd/otelcorecol
  name: otelcorecol
  description: Local OpenTelemetry Collector binary, testing only.
  version: 0.63.1-dev
  otelcol_version: 0.63.1

receivers:
  - gomod: go.opentelemetry.io/collector/receiver/otlpreceiver v0.63.1
exporters:
  - gomod: go.opentelemetry.io/collector/exporter/loggingexporter v0.63.1
  - gomod: go.opentelemetry.io/collector/exporter/otlpexporter v0.63.1
  - gomod: go.opentelemetry.io/collector/exporter/otlphttpexporter v0.63.1
extensions:
  - import: go.opentelemetry.io/collector/extension/ballastextension
    gomod: go.opentelemetry.io/collector v0.63.1
  - import: go.opentelemetry.io/collector/extension/zpagesextension
    gomod: go.opentelemetry.io/collector v0.63.1
processors:
  - import: go.opentelemetry.io/collector/processor/batchprocessor
    gomod: go.opentelemetry.io/collector v0.63.1
  - import: go.opentelemetry.io/collector/processor/memorylimiterprocessor
    gomod: go.opentelemetry.io/collector v0.63.1

replaces:
  - go.opentelemetry.io/collector => ../../
  - go.opentelemetry.io/collector/exporter/loggingexporter => ../../exporter/loggingexporter
  - go.opentelemetry.io/collector/exporter/otlpexporter => ../../exporter/otlpexporter
  - go.opentelemetry.io/collector/exporter/otlphttpexporter => ../../exporter/otlphttpexporter
  - go.opentelemetry.io/collector/semconv => ../../semconv
  - go.opentelemetry.io/collector/receiver/otlpreceiver => ../../receiver/otlpreceiver
  - go.opentelemetry.io/collector/pdata => ../../pdata
