# One of 'breaking', 'deprecation', 'new_component', 'enhancement', 'bug_fix'
change_type: enhancement

# The name of the component, or a single word describing the area of concern, (e.g. otlpreceiver)
component: config/configopaque

# A brief description of the change.  Surround your text with quotes ("") if it needs to start with a backtick (`).
note: Add new `configopaque.String` type alias for opaque strings.

# One or more tracking issues or pull requests related to the change
issues: [5653]
