# One of 'breaking', 'deprecation', 'new_component', 'enhancement', 'bug_fix'
change_type: enhancement

# The name of the component, or a single word describing the area of concern, (e.g. otlpreceiver)
component: batchprocessor

note: Support zero timeout.

issues: [7508]

subtext: This allows the batchprocessor to limit request sizes without introducing delay in a pipeline, to act only as a splitter.
